spring:
  application.name: turbine

security.basic.enabled: false

#表示它会把所有微服务名称是product-view-service-feign 的实例信息都收集起来
turbine:
  aggregator:
    clusterConfig: default
  appConfig: product-view-service-feign  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/